### ISSUE TITLE
qb-hud/client/main.lua:88: attempt to index a nil value (field 'proximity')

### ISSUE THREAD

**Issue by haitham1337** [qbcore-fivem/qb-hud#1]
this error show with me
qb-hud/client/main.lua:88: attempt to index a nil value (field 'proximity')

Does it have anything to do with the update inventory ?
It appeared after yesterday's update

**Comment by kentjuno** [comment]
turn on one-sync ya.


> this error show with me
> qb-hud/client/main.lua:88: attempt to index a nil value (field 'proximity')
> 
> Does it have anything to do with the update inventory ?
> It appeared after yesterday's update

**Comment by JericoFX** [comment]
Check github, under Voice channel
