### ISSUE TITLE
Hud

### ISSUE THREAD

**Issue by Temouchenty** [qbcore-fivem/qb-hud#10]
the hud is not compatible with smaller screen can you fix it please and if you can add tokovoip function for those who work with teamspeak

**Comment by BerkieBb** [comment]
tokovoip is a no, the hud scaling with smaller/bigger screens than 1080p has been fixed but the fix has not been pushed yet, that will come soon with a style update

**Comment by Temouchenty** [comment]
okay bro Keep pushing <3
