### ISSUE TITLE
Seatbelt Icon Color

### ISSUE THREAD

**Issue by bosskitz** [qbcore-fivem/qb-hud#17]
If players gets thrown out, once players gats back to vehicle, seatbelt icon stays on even is player is not really on seatbelt.
End result, the player's seatbelt icon now acts the other way around where player is not on seatbelt but the icon is on.

qb-hud and qb-smallresources are up to date.

**Comment by GhzGarage** [comment]
Not a hud issue. It’s seatbelt. Go open issue there
