### ISSUE TITLE
Reintroduced proximity nil bug #5

### ISSUE THREAD

**Issue by codygulley** [qbcore-fivem/qb-hud#19]
Looks like  [this commit](https://github.com/qbcore-framework/qb-hud/commit/068088c5aeacc4eb03c386545b6ecbdfb612f300#diff-bd3d5f0dfcec5f757b1cb2b6ec16fd75bb5ead988fed33033896aaf1a00e4a0d) overwrote the fix for issue #5  that was merged in PR  #9.

**Comment by HydrixScripts** [comment]
you ever find a fix can you tell me which line and where to edit nil value?

**Comment by codygulley** [comment]
@imtorchedbud  see https://github.com/codygulley/qb-hud/commit/31e46e7e7bea9fa31d3bff912e02da87c0dcd406

**Comment by GhzGarage** [comment]
Still trying to reproduce this

**Comment by OfficiallyM** [comment]
Curiously this didn't occur on my development server, but did in production. Can confirm #9 fixes the problem, so should probably get re-added back.

**Comment by GhzGarage** [comment]
Done
