### ISSUE TITLE
im run onesync infinty

### ISSUE THREAD

**Issue by haitham1337** [qbcore-fivem/qb-hud#5]
Is it possible to put a conditional sentence so that everything does not stop qb-hud?
in case it stops proximity  does not stop all qb-hud

https://imgur.com/GcIAsEW
https://i.imgur.com/JEsZZrG.png

**Comment by GhzGarage** [comment]
The voice icon does not work without infinity

**Comment by haitham1337** [comment]
Yes it works for me on onesync infinity
But sometimes it stops
@GhzGarage

**Comment by codygulley** [comment]
From my team's testing this issue only occurred on the first login of a user after a server restart. The fix I've implemented is to check if the key is nil , if so use a default value (0) rather than erroring.
